package model.View;

import model.entity.MnjCourierInformationLineEOImpl;

import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 17 11:14:59 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjCourierInformationLineVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        CourierId {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getCourierId();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setCourierId((Number)value);
            }
        }
        ,
        AwbId {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getAwbId();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setAwbId((String)value);
            }
        }
        ,
        CourierName {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getCourierName();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setCourierName((String)value);
            }
        }
        ,
        ImportExport {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getImportExport();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setImportExport((String)value);
            }
        }
        ,
        CourierDate {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getCourierDate();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setCourierDate((Date)value);
            }
        }
        ,
        Buyer {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getBuyer();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setBuyer((String)value);
            }
        }
        ,
        Season {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getSeason();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setSeason((String)value);
            }
        }
        ,
        ItemCode {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getItemCode();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setItemCode((String)value);
            }
        }
        ,
        Qty {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getQty();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setQty((Number)value);
            }
        }
        ,
        OrgId {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getOrgId();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setOrgId((Number)value);
            }
        }
        ,
        ConcigneeUnit {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getConcigneeUnit();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setConcigneeUnit((String)value);
            }
        }
        ,
        PayeeUnit {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getPayeeUnit();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setPayeeUnit((String)value);
            }
        }
        ,
        SupplierCountry {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getSupplierCountry();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setSupplierCountry((String)value);
            }
        }
        ,
        ValuePrice {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getValuePrice();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setValuePrice((Number)value);
            }
        }
        ,
        Currency {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getCurrency();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setCurrency((String)value);
            }
        }
        ,
        PackageQty {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getPackageQty();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setPackageQty((Number)value);
            }
        }
        ,
        Item {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getItem();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setItem((String)value);
            }
        }
        ,
        CnfAgentName {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getCnfAgentName();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setCnfAgentName((String)value);
            }
        }
        ,
        ProcessIndicatorFlag {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getProcessIndicatorFlag();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setProcessIndicatorFlag((String)value);
            }
        }
        ,
        MerchantReceivedBy {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getMerchantReceivedBy();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setMerchantReceivedBy((String)value);
            }
        }
        ,
        QtyYard {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getQtyYard();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setQtyYard((Number)value);
            }
        }
        ,
        StdPrice {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getStdPrice();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setStdPrice((Number)value);
            }
        }
        ,
        TotalBudgetQty {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getTotalBudgetQty();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setTotalBudgetQty((Number)value);
            }
        }
        ,
        Consumption {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getConsumption();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setConsumption((Number)value);
            }
        }
        ,
        Status {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getStatus();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setStatus((Number)value);
            }
        }
        ,
        Status1 {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getStatus1();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setStatus1((String)value);
            }
        }
        ,
        StatusDetail {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getStatusDetail();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setStatusDetail((String)value);
            }
        }
        ,
        HeaderId {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getHeaderId();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setHeaderId((Number)value);
            }
        }
        ,
        BuyerId {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getBuyerId();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setBuyerId((Number)value);
            }
        }
        ,
        DevSampleBulk {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getDevSampleBulk();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setDevSampleBulk((String)value);
            }
        }
        ,
        Unit {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getUnit();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setUnit((String)value);
            }
        }
        ,
        SenderUnit {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getSenderUnit();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setSenderUnit((String)value);
            }
        }
        ,
        DeliveryLocation {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getDeliveryLocation();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setDeliveryLocation((String)value);
            }
        }
        ,
        UserName {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getUserName();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setUserName((String)value);
            }
        }
        ,
        StyleNumber {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getStyleNumber();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setStyleNumber((String)value);
            }
        }
        ,
        BpoNumber {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getBpoNumber();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setBpoNumber((String)value);
            }
        }
        ,
        DocRcvdDate {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getDocRcvdDate();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setDocRcvdDate((Date)value);
            }
        }
        ,
        ExpectedDeliveryDate {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getExpectedDeliveryDate();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setExpectedDeliveryDate((Date)value);
            }
        }
        ,
        ActualDeliveryDate {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getActualDeliveryDate();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setActualDeliveryDate((Date)value);
            }
        }
        ,
        SampleDocNo {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getSampleDocNo();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setSampleDocNo((Number)value);
            }
        }
        ,
        VersionNo {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getVersionNo();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setVersionNo((Number)value);
            }
        }
        ,
        VersionDate {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getVersionDate();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setVersionDate((Date)value);
            }
        }
        ,
        RespId {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getRespId();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setRespId((Number)value);
            }
        }
        ,
        UserId {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getUserId();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setUserId((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        LastUpdateDate {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getLastUpdateDate();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setLastUpdateDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        Uom {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getUom();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setUom((String)value);
            }
        }
        ,
        KnowStyle {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getKnowStyle();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setKnowStyle((String)value);
            }
        }
        ,
        InvoiceNo {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getInvoiceNo();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setInvoiceNo((String)value);
            }
        }
        ,
        InvoiceDate {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getInvoiceDate();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setInvoiceDate((Date)value);
            }
        }
        ,
        Weight {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getWeight();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setWeight((Number)value);
            }
        }
        ,
        WeightType {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getWeightType();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setWeightType((String)value);
            }
        }
        ,
        UdNo {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getUdNo();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setUdNo((String)value);
            }
        }
        ,
        ExportLcNo {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getExportLcNo();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setExportLcNo((String)value);
            }
        }
        ,
        DocHandoverDate {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getDocHandoverDate();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setDocHandoverDate((Date)value);
            }
        }
        ,
        DeliveryDate {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getDeliveryDate();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setDeliveryDate((Date)value);
            }
        }
        ,
        Remarks {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getRemarks();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        RemarksCommercial {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getRemarksCommercial();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setRemarksCommercial((String)value);
            }
        }
        ,
        NeedDetails {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getNeedDetails();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setNeedDetails((String)value);
            }
        }
        ,
        NeedDetailsCommercial {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getNeedDetailsCommercial();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setNeedDetailsCommercial((String)value);
            }
        }
        ,
        CompletionFlag {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getCompletionFlag();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setCompletionFlag((String)value);
            }
        }
        ,
        CompletionFlagCommercial {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getCompletionFlagCommercial();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setCompletionFlagCommercial((String)value);
            }
        }
        ,
        ProcessIndicatorCommerFlag {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getProcessIndicatorCommerFlag();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setProcessIndicatorCommerFlag((String)value);
            }
        }
        ,
        CostCenterCode {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getCostCenterCode();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setCostCenterCode((Number)value);
            }
        }
        ,
        ItemCodeCombination {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getItemCodeCombination();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setItemCodeCombination((String)value);
            }
        }
        ,
        TotBudgetAmt {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getTotBudgetAmt();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setTotBudgetAmt((Number)value);
            }
        }
        ,
        Amount {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getAmount();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setAmount((Number)value);
            }
        }
        ,
        StatusLOV1 {
            public Object get(MnjCourierInformationLineVORowImpl obj) {
                return obj.getStatusLOV1();
            }

            public void put(MnjCourierInformationLineVORowImpl obj,
                            Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(MnjCourierInformationLineVORowImpl object);

        public abstract void put(MnjCourierInformationLineVORowImpl object,
                                 Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int COURIERID = AttributesEnum.CourierId.index();
    public static final int AWBID = AttributesEnum.AwbId.index();
    public static final int COURIERNAME = AttributesEnum.CourierName.index();
    public static final int IMPORTEXPORT = AttributesEnum.ImportExport.index();
    public static final int COURIERDATE = AttributesEnum.CourierDate.index();
    public static final int BUYER = AttributesEnum.Buyer.index();
    public static final int SEASON = AttributesEnum.Season.index();
    public static final int ITEMCODE = AttributesEnum.ItemCode.index();
    public static final int QTY = AttributesEnum.Qty.index();
    public static final int ORGID = AttributesEnum.OrgId.index();
    public static final int CONCIGNEEUNIT = AttributesEnum.ConcigneeUnit.index();
    public static final int PAYEEUNIT = AttributesEnum.PayeeUnit.index();
    public static final int SUPPLIERCOUNTRY = AttributesEnum.SupplierCountry.index();
    public static final int VALUEPRICE = AttributesEnum.ValuePrice.index();
    public static final int CURRENCY = AttributesEnum.Currency.index();
    public static final int PACKAGEQTY = AttributesEnum.PackageQty.index();
    public static final int ITEM = AttributesEnum.Item.index();
    public static final int CNFAGENTNAME = AttributesEnum.CnfAgentName.index();
    public static final int PROCESSINDICATORFLAG = AttributesEnum.ProcessIndicatorFlag.index();
    public static final int MERCHANTRECEIVEDBY = AttributesEnum.MerchantReceivedBy.index();
    public static final int QTYYARD = AttributesEnum.QtyYard.index();
    public static final int STDPRICE = AttributesEnum.StdPrice.index();
    public static final int TOTALBUDGETQTY = AttributesEnum.TotalBudgetQty.index();
    public static final int CONSUMPTION = AttributesEnum.Consumption.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int STATUS1 = AttributesEnum.Status1.index();
    public static final int STATUSDETAIL = AttributesEnum.StatusDetail.index();
    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int BUYERID = AttributesEnum.BuyerId.index();
    public static final int DEVSAMPLEBULK = AttributesEnum.DevSampleBulk.index();
    public static final int UNIT = AttributesEnum.Unit.index();
    public static final int SENDERUNIT = AttributesEnum.SenderUnit.index();
    public static final int DELIVERYLOCATION = AttributesEnum.DeliveryLocation.index();
    public static final int USERNAME = AttributesEnum.UserName.index();
    public static final int STYLENUMBER = AttributesEnum.StyleNumber.index();
    public static final int BPONUMBER = AttributesEnum.BpoNumber.index();
    public static final int DOCRCVDDATE = AttributesEnum.DocRcvdDate.index();
    public static final int EXPECTEDDELIVERYDATE = AttributesEnum.ExpectedDeliveryDate.index();
    public static final int ACTUALDELIVERYDATE = AttributesEnum.ActualDeliveryDate.index();
    public static final int SAMPLEDOCNO = AttributesEnum.SampleDocNo.index();
    public static final int VERSIONNO = AttributesEnum.VersionNo.index();
    public static final int VERSIONDATE = AttributesEnum.VersionDate.index();
    public static final int RESPID = AttributesEnum.RespId.index();
    public static final int USERID = AttributesEnum.UserId.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int UOM = AttributesEnum.Uom.index();
    public static final int KNOWSTYLE = AttributesEnum.KnowStyle.index();
    public static final int INVOICENO = AttributesEnum.InvoiceNo.index();
    public static final int INVOICEDATE = AttributesEnum.InvoiceDate.index();
    public static final int WEIGHT = AttributesEnum.Weight.index();
    public static final int WEIGHTTYPE = AttributesEnum.WeightType.index();
    public static final int UDNO = AttributesEnum.UdNo.index();
    public static final int EXPORTLCNO = AttributesEnum.ExportLcNo.index();
    public static final int DOCHANDOVERDATE = AttributesEnum.DocHandoverDate.index();
    public static final int DELIVERYDATE = AttributesEnum.DeliveryDate.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int REMARKSCOMMERCIAL = AttributesEnum.RemarksCommercial.index();
    public static final int NEEDDETAILS = AttributesEnum.NeedDetails.index();
    public static final int NEEDDETAILSCOMMERCIAL = AttributesEnum.NeedDetailsCommercial.index();
    public static final int COMPLETIONFLAG = AttributesEnum.CompletionFlag.index();
    public static final int COMPLETIONFLAGCOMMERCIAL = AttributesEnum.CompletionFlagCommercial.index();
    public static final int PROCESSINDICATORCOMMERFLAG = AttributesEnum.ProcessIndicatorCommerFlag.index();
    public static final int COSTCENTERCODE = AttributesEnum.CostCenterCode.index();
    public static final int ITEMCODECOMBINATION = AttributesEnum.ItemCodeCombination.index();
    public static final int TOTBUDGETAMT = AttributesEnum.TotBudgetAmt.index();
    public static final int AMOUNT = AttributesEnum.Amount.index();
    public static final int STATUSLOV1 = AttributesEnum.StatusLOV1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public MnjCourierInformationLineVORowImpl() {
    }

    /**
     * Gets MnjCourierInformationLineEO entity object.
     * @return the MnjCourierInformationLineEO
     */
    public MnjCourierInformationLineEOImpl getMnjCourierInformationLineEO() {
        return (MnjCourierInformationLineEOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for COURIER_ID using the alias name CourierId.
     * @return the COURIER_ID
     */
    public Number getCourierId() {
        return (Number) getAttributeInternal(COURIERID);
    }

    /**
     * Sets <code>value</code> as attribute value for COURIER_ID using the alias name CourierId.
     * @param value value to set the COURIER_ID
     */
    public void setCourierId(Number value) {
        setAttributeInternal(COURIERID, value);
    }

    /**
     * Gets the attribute value for AWB_ID using the alias name AwbId.
     * @return the AWB_ID
     */
    public String getAwbId() {
        return (String) getAttributeInternal(AWBID);
    }

    /**
     * Sets <code>value</code> as attribute value for AWB_ID using the alias name AwbId.
     * @param value value to set the AWB_ID
     */
    public void setAwbId(String value) {
        setAttributeInternal(AWBID, value);
    }

    /**
     * Gets the attribute value for COURIER_NAME using the alias name CourierName.
     * @return the COURIER_NAME
     */
    public String getCourierName() {
        return (String) getAttributeInternal(COURIERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for COURIER_NAME using the alias name CourierName.
     * @param value value to set the COURIER_NAME
     */
    public void setCourierName(String value) {
        setAttributeInternal(COURIERNAME, value);
    }

    /**
     * Gets the attribute value for IMPORT_EXPORT using the alias name ImportExport.
     * @return the IMPORT_EXPORT
     */
    public String getImportExport() {
        return (String) getAttributeInternal(IMPORTEXPORT);
    }

    /**
     * Sets <code>value</code> as attribute value for IMPORT_EXPORT using the alias name ImportExport.
     * @param value value to set the IMPORT_EXPORT
     */
    public void setImportExport(String value) {
        setAttributeInternal(IMPORTEXPORT, value);
    }

    /**
     * Gets the attribute value for COURIER_DATE using the alias name CourierDate.
     * @return the COURIER_DATE
     */
    public Date getCourierDate() {
        return (Date) getAttributeInternal(COURIERDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for COURIER_DATE using the alias name CourierDate.
     * @param value value to set the COURIER_DATE
     */
    public void setCourierDate(Date value) {
        setAttributeInternal(COURIERDATE, value);
    }

    /**
     * Gets the attribute value for BUYER using the alias name Buyer.
     * @return the BUYER
     */
    public String getBuyer() {
        return (String) getAttributeInternal(BUYER);
    }

    /**
     * Sets <code>value</code> as attribute value for BUYER using the alias name Buyer.
     * @param value value to set the BUYER
     */
    public void setBuyer(String value) {
        setAttributeInternal(BUYER, value);
    }

    /**
     * Gets the attribute value for SEASON using the alias name Season.
     * @return the SEASON
     */
    public String getSeason() {
        return (String) getAttributeInternal(SEASON);
    }

    /**
     * Sets <code>value</code> as attribute value for SEASON using the alias name Season.
     * @param value value to set the SEASON
     */
    public void setSeason(String value) {
        setAttributeInternal(SEASON, value);
    }

    /**
     * Gets the attribute value for ITEM_CODE using the alias name ItemCode.
     * @return the ITEM_CODE
     */
    public String getItemCode() {
        return (String) getAttributeInternal(ITEMCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_CODE using the alias name ItemCode.
     * @param value value to set the ITEM_CODE
     */
    public void setItemCode(String value) {
        setAttributeInternal(ITEMCODE, value);
    }

    /**
     * Gets the attribute value for QTY using the alias name Qty.
     * @return the QTY
     */
    public Number getQty() {
        return (Number) getAttributeInternal(QTY);
    }

    /**
     * Sets <code>value</code> as attribute value for QTY using the alias name Qty.
     * @param value value to set the QTY
     */
    public void setQty(Number value) {
        setAttributeInternal(QTY, value);
    }

    /**
     * Gets the attribute value for ORG_ID using the alias name OrgId.
     * @return the ORG_ID
     */
    public Number getOrgId() {
        return (Number) getAttributeInternal(ORGID);
    }

    /**
     * Sets <code>value</code> as attribute value for ORG_ID using the alias name OrgId.
     * @param value value to set the ORG_ID
     */
    public void setOrgId(Number value) {
        setAttributeInternal(ORGID, value);
    }

    /**
     * Gets the attribute value for CONCIGNEE_UNIT using the alias name ConcigneeUnit.
     * @return the CONCIGNEE_UNIT
     */
    public String getConcigneeUnit() {
        return (String) getAttributeInternal(CONCIGNEEUNIT);
    }

    /**
     * Sets <code>value</code> as attribute value for CONCIGNEE_UNIT using the alias name ConcigneeUnit.
     * @param value value to set the CONCIGNEE_UNIT
     */
    public void setConcigneeUnit(String value) {
        setAttributeInternal(CONCIGNEEUNIT, value);
    }

    /**
     * Gets the attribute value for PAYEE_UNIT using the alias name PayeeUnit.
     * @return the PAYEE_UNIT
     */
    public String getPayeeUnit() {
        return (String) getAttributeInternal(PAYEEUNIT);
    }

    /**
     * Sets <code>value</code> as attribute value for PAYEE_UNIT using the alias name PayeeUnit.
     * @param value value to set the PAYEE_UNIT
     */
    public void setPayeeUnit(String value) {
        setAttributeInternal(PAYEEUNIT, value);
    }

    /**
     * Gets the attribute value for SUPPLIER_COUNTRY using the alias name SupplierCountry.
     * @return the SUPPLIER_COUNTRY
     */
    public String getSupplierCountry() {
        return (String) getAttributeInternal(SUPPLIERCOUNTRY);
    }

    /**
     * Sets <code>value</code> as attribute value for SUPPLIER_COUNTRY using the alias name SupplierCountry.
     * @param value value to set the SUPPLIER_COUNTRY
     */
    public void setSupplierCountry(String value) {
        setAttributeInternal(SUPPLIERCOUNTRY, value);
    }

    /**
     * Gets the attribute value for VALUE_PRICE using the alias name ValuePrice.
     * @return the VALUE_PRICE
     */
    public Number getValuePrice() {
        return (Number) getAttributeInternal(VALUEPRICE);
    }

    /**
     * Sets <code>value</code> as attribute value for VALUE_PRICE using the alias name ValuePrice.
     * @param value value to set the VALUE_PRICE
     */
    public void setValuePrice(Number value) {
        setAttributeInternal(VALUEPRICE, value);
    }

    /**
     * Gets the attribute value for CURRENCY using the alias name Currency.
     * @return the CURRENCY
     */
    public String getCurrency() {
        return (String) getAttributeInternal(CURRENCY);
    }

    /**
     * Sets <code>value</code> as attribute value for CURRENCY using the alias name Currency.
     * @param value value to set the CURRENCY
     */
    public void setCurrency(String value) {
        setAttributeInternal(CURRENCY, value);
    }

    /**
     * Gets the attribute value for PACKAGE_QTY using the alias name PackageQty.
     * @return the PACKAGE_QTY
     */
    public Number getPackageQty() {
        return (Number) getAttributeInternal(PACKAGEQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for PACKAGE_QTY using the alias name PackageQty.
     * @param value value to set the PACKAGE_QTY
     */
    public void setPackageQty(Number value) {
        setAttributeInternal(PACKAGEQTY, value);
    }

    /**
     * Gets the attribute value for ITEM using the alias name Item.
     * @return the ITEM
     */
    public String getItem() {
        return (String) getAttributeInternal(ITEM);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM using the alias name Item.
     * @param value value to set the ITEM
     */
    public void setItem(String value) {
        setAttributeInternal(ITEM, value);
    }

    /**
     * Gets the attribute value for CNF_AGENT_NAME using the alias name CnfAgentName.
     * @return the CNF_AGENT_NAME
     */
    public String getCnfAgentName() {
        return (String) getAttributeInternal(CNFAGENTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for CNF_AGENT_NAME using the alias name CnfAgentName.
     * @param value value to set the CNF_AGENT_NAME
     */
    public void setCnfAgentName(String value) {
        setAttributeInternal(CNFAGENTNAME, value);
    }

    /**
     * Gets the attribute value for PROCESS_INDICATOR_FLAG using the alias name ProcessIndicatorFlag.
     * @return the PROCESS_INDICATOR_FLAG
     */
    public String getProcessIndicatorFlag() {
        return (String) getAttributeInternal(PROCESSINDICATORFLAG);
    }

    /**
     * Sets <code>value</code> as attribute value for PROCESS_INDICATOR_FLAG using the alias name ProcessIndicatorFlag.
     * @param value value to set the PROCESS_INDICATOR_FLAG
     */
    public void setProcessIndicatorFlag(String value) {
        setAttributeInternal(PROCESSINDICATORFLAG, value);
    }

    /**
     * Gets the attribute value for MERCHANT_RECEIVED_BY using the alias name MerchantReceivedBy.
     * @return the MERCHANT_RECEIVED_BY
     */
    public String getMerchantReceivedBy() {
        return (String) getAttributeInternal(MERCHANTRECEIVEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for MERCHANT_RECEIVED_BY using the alias name MerchantReceivedBy.
     * @param value value to set the MERCHANT_RECEIVED_BY
     */
    public void setMerchantReceivedBy(String value) {
        setAttributeInternal(MERCHANTRECEIVEDBY, value);
    }

    /**
     * Gets the attribute value for QTY_YARD using the alias name QtyYard.
     * @return the QTY_YARD
     */
    public Number getQtyYard() {
        return (Number) getAttributeInternal(QTYYARD);
    }

    /**
     * Sets <code>value</code> as attribute value for QTY_YARD using the alias name QtyYard.
     * @param value value to set the QTY_YARD
     */
    public void setQtyYard(Number value) {
        setAttributeInternal(QTYYARD, value);
    }

    /**
     * Gets the attribute value for STD_PRICE using the alias name StdPrice.
     * @return the STD_PRICE
     */
    public Number getStdPrice() {
        return (Number) getAttributeInternal(STDPRICE);
    }

    /**
     * Sets <code>value</code> as attribute value for STD_PRICE using the alias name StdPrice.
     * @param value value to set the STD_PRICE
     */
    public void setStdPrice(Number value) {
        setAttributeInternal(STDPRICE, value);
    }

    /**
     * Gets the attribute value for TOTAL_BUDGET_QTY using the alias name TotalBudgetQty.
     * @return the TOTAL_BUDGET_QTY
     */
    public Number getTotalBudgetQty() {
        return (Number) getAttributeInternal(TOTALBUDGETQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_BUDGET_QTY using the alias name TotalBudgetQty.
     * @param value value to set the TOTAL_BUDGET_QTY
     */
    public void setTotalBudgetQty(Number value) {
        setAttributeInternal(TOTALBUDGETQTY, value);
    }

    /**
     * Gets the attribute value for CONSUMPTION using the alias name Consumption.
     * @return the CONSUMPTION
     */
    public Number getConsumption() {
        return (Number) getAttributeInternal(CONSUMPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for CONSUMPTION using the alias name Consumption.
     * @param value value to set the CONSUMPTION
     */
    public void setConsumption(Number value) {
        setAttributeInternal(CONSUMPTION, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public Number getStatus() {
        return (Number) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(Number value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StatusDetail.
     * @return the StatusDetail
     */
    public String getStatusDetail() {
        return (String) getAttributeInternal(STATUSDETAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StatusDetail.
     * @param value value to set the  StatusDetail
     */
    public void setStatusDetail(String value) {
        setAttributeInternal(STATUSDETAIL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute HeaderId.
     * @return the HeaderId
     */
    public Number getHeaderId() {
        return (Number) getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute HeaderId.
     * @param value value to set the  HeaderId
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BuyerId.
     * @return the BuyerId
     */
    public Number getBuyerId() {
        return (Number) getAttributeInternal(BUYERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BuyerId.
     * @param value value to set the  BuyerId
     */
    public void setBuyerId(Number value) {
        setAttributeInternal(BUYERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DevSampleBulk.
     * @return the DevSampleBulk
     */
    public String getDevSampleBulk() {
        return (String) getAttributeInternal(DEVSAMPLEBULK);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DevSampleBulk.
     * @param value value to set the  DevSampleBulk
     */
    public void setDevSampleBulk(String value) {
        setAttributeInternal(DEVSAMPLEBULK, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Unit.
     * @return the Unit
     */
    public String getUnit() {
        return (String) getAttributeInternal(UNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Unit.
     * @param value value to set the  Unit
     */
    public void setUnit(String value) {
        setAttributeInternal(UNIT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SenderUnit.
     * @return the SenderUnit
     */
    public String getSenderUnit() {
        return (String) getAttributeInternal(SENDERUNIT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SenderUnit.
     * @param value value to set the  SenderUnit
     */
    public void setSenderUnit(String value) {
        setAttributeInternal(SENDERUNIT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DeliveryLocation.
     * @return the DeliveryLocation
     */
    public String getDeliveryLocation() {
        return (String) getAttributeInternal(DELIVERYLOCATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DeliveryLocation.
     * @param value value to set the  DeliveryLocation
     */
    public void setDeliveryLocation(String value) {
        setAttributeInternal(DELIVERYLOCATION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UserName.
     * @return the UserName
     */
    public String getUserName() {
        return (String) getAttributeInternal(USERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UserName.
     * @param value value to set the  UserName
     */
    public void setUserName(String value) {
        setAttributeInternal(USERNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StyleNumber.
     * @return the StyleNumber
     */
    public String getStyleNumber() {
        return (String) getAttributeInternal(STYLENUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StyleNumber.
     * @param value value to set the  StyleNumber
     */
    public void setStyleNumber(String value) {
        setAttributeInternal(STYLENUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BpoNumber.
     * @return the BpoNumber
     */
    public String getBpoNumber() {
        return (String) getAttributeInternal(BPONUMBER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BpoNumber.
     * @param value value to set the  BpoNumber
     */
    public void setBpoNumber(String value) {
        setAttributeInternal(BPONUMBER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DocRcvdDate.
     * @return the DocRcvdDate
     */
    public Date getDocRcvdDate() {
        return (Date) getAttributeInternal(DOCRCVDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DocRcvdDate.
     * @param value value to set the  DocRcvdDate
     */
    public void setDocRcvdDate(Date value) {
        setAttributeInternal(DOCRCVDDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ExpectedDeliveryDate.
     * @return the ExpectedDeliveryDate
     */
    public Date getExpectedDeliveryDate() {
        return (Date) getAttributeInternal(EXPECTEDDELIVERYDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ExpectedDeliveryDate.
     * @param value value to set the  ExpectedDeliveryDate
     */
    public void setExpectedDeliveryDate(Date value) {
        setAttributeInternal(EXPECTEDDELIVERYDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ActualDeliveryDate.
     * @return the ActualDeliveryDate
     */
    public Date getActualDeliveryDate() {
        return (Date) getAttributeInternal(ACTUALDELIVERYDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ActualDeliveryDate.
     * @param value value to set the  ActualDeliveryDate
     */
    public void setActualDeliveryDate(Date value) {
        setAttributeInternal(ACTUALDELIVERYDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SampleDocNo.
     * @return the SampleDocNo
     */
    public Number getSampleDocNo() {
        return (Number) getAttributeInternal(SAMPLEDOCNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SampleDocNo.
     * @param value value to set the  SampleDocNo
     */
    public void setSampleDocNo(Number value) {
        setAttributeInternal(SAMPLEDOCNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute VersionNo.
     * @return the VersionNo
     */
    public Number getVersionNo() {
        return (Number) getAttributeInternal(VERSIONNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute VersionNo.
     * @param value value to set the  VersionNo
     */
    public void setVersionNo(Number value) {
        setAttributeInternal(VERSIONNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute VersionDate.
     * @return the VersionDate
     */
    public Date getVersionDate() {
        return (Date) getAttributeInternal(VERSIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute VersionDate.
     * @param value value to set the  VersionDate
     */
    public void setVersionDate(Date value) {
        setAttributeInternal(VERSIONDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RespId.
     * @return the RespId
     */
    public Number getRespId() {
        return (Number) getAttributeInternal(RESPID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RespId.
     * @param value value to set the  RespId
     */
    public void setRespId(Number value) {
        setAttributeInternal(RESPID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UserId.
     * @return the UserId
     */
    public Number getUserId() {
        return (Number) getAttributeInternal(USERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UserId.
     * @param value value to set the  UserId
     */
    public void setUserId(Number value) {
        setAttributeInternal(USERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreationDate.
     * @return the CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreationDate.
     * @param value value to set the  CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreatedBy.
     * @return the CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreatedBy.
     * @param value value to set the  CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdateDate.
     * @return the LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdateDate.
     * @param value value to set the  LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LastUpdatedBy.
     * @return the LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LastUpdatedBy.
     * @param value value to set the  LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Uom.
     * @return the Uom
     */
    public String getUom() {
        return (String) getAttributeInternal(UOM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Uom.
     * @param value value to set the  Uom
     */
    public void setUom(String value) {
        setAttributeInternal(UOM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute KnowStyle.
     * @return the KnowStyle
     */
    public String getKnowStyle() {
        return (String) getAttributeInternal(KNOWSTYLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute KnowStyle.
     * @param value value to set the  KnowStyle
     */
    public void setKnowStyle(String value) {
        setAttributeInternal(KNOWSTYLE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoiceNo.
     * @return the InvoiceNo
     */
    public String getInvoiceNo() {
        return (String) getAttributeInternal(INVOICENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvoiceNo.
     * @param value value to set the  InvoiceNo
     */
    public void setInvoiceNo(String value) {
        setAttributeInternal(INVOICENO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute InvoiceDate.
     * @return the InvoiceDate
     */
    public Date getInvoiceDate() {
        return (Date) getAttributeInternal(INVOICEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute InvoiceDate.
     * @param value value to set the  InvoiceDate
     */
    public void setInvoiceDate(Date value) {
        setAttributeInternal(INVOICEDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Weight.
     * @return the Weight
     */
    public Number getWeight() {
        return (Number) getAttributeInternal(WEIGHT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Weight.
     * @param value value to set the  Weight
     */
    public void setWeight(Number value) {
        setAttributeInternal(WEIGHT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute WeightType.
     * @return the WeightType
     */
    public String getWeightType() {
        return (String) getAttributeInternal(WEIGHTTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WeightType.
     * @param value value to set the  WeightType
     */
    public void setWeightType(String value) {
        setAttributeInternal(WEIGHTTYPE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute UdNo.
     * @return the UdNo
     */
    public String getUdNo() {
        return (String) getAttributeInternal(UDNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute UdNo.
     * @param value value to set the  UdNo
     */
    public void setUdNo(String value) {
        setAttributeInternal(UDNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ExportLcNo.
     * @return the ExportLcNo
     */
    public String getExportLcNo() {
        return (String) getAttributeInternal(EXPORTLCNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ExportLcNo.
     * @param value value to set the  ExportLcNo
     */
    public void setExportLcNo(String value) {
        setAttributeInternal(EXPORTLCNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DocHandoverDate.
     * @return the DocHandoverDate
     */
    public Date getDocHandoverDate() {
        return (Date) getAttributeInternal(DOCHANDOVERDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DocHandoverDate.
     * @param value value to set the  DocHandoverDate
     */
    public void setDocHandoverDate(Date value) {
        setAttributeInternal(DOCHANDOVERDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DeliveryDate.
     * @return the DeliveryDate
     */
    public Date getDeliveryDate() {
        return (Date) getAttributeInternal(DELIVERYDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DeliveryDate.
     * @param value value to set the  DeliveryDate
     */
    public void setDeliveryDate(Date value) {
        setAttributeInternal(DELIVERYDATE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Remarks.
     * @return the Remarks
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Remarks.
     * @param value value to set the  Remarks
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RemarksCommercial.
     * @return the RemarksCommercial
     */
    public String getRemarksCommercial() {
        return (String) getAttributeInternal(REMARKSCOMMERCIAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RemarksCommercial.
     * @param value value to set the  RemarksCommercial
     */
    public void setRemarksCommercial(String value) {
        setAttributeInternal(REMARKSCOMMERCIAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute NeedDetails.
     * @return the NeedDetails
     */
    public String getNeedDetails() {
        return (String) getAttributeInternal(NEEDDETAILS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute NeedDetails.
     * @param value value to set the  NeedDetails
     */
    public void setNeedDetails(String value) {
        setAttributeInternal(NEEDDETAILS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute NeedDetailsCommercial.
     * @return the NeedDetailsCommercial
     */
    public String getNeedDetailsCommercial() {
        return (String) getAttributeInternal(NEEDDETAILSCOMMERCIAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute NeedDetailsCommercial.
     * @param value value to set the  NeedDetailsCommercial
     */
    public void setNeedDetailsCommercial(String value) {
        setAttributeInternal(NEEDDETAILSCOMMERCIAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CompletionFlag.
     * @return the CompletionFlag
     */
    public String getCompletionFlag() {
        return (String) getAttributeInternal(COMPLETIONFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CompletionFlag.
     * @param value value to set the  CompletionFlag
     */
    public void setCompletionFlag(String value) {
        setAttributeInternal(COMPLETIONFLAG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CompletionFlagCommercial.
     * @return the CompletionFlagCommercial
     */
    public String getCompletionFlagCommercial() {
        return (String) getAttributeInternal(COMPLETIONFLAGCOMMERCIAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CompletionFlagCommercial.
     * @param value value to set the  CompletionFlagCommercial
     */
    public void setCompletionFlagCommercial(String value) {
        setAttributeInternal(COMPLETIONFLAGCOMMERCIAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ProcessIndicatorCommerFlag.
     * @return the ProcessIndicatorCommerFlag
     */
    public String getProcessIndicatorCommerFlag() {
        return (String) getAttributeInternal(PROCESSINDICATORCOMMERFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ProcessIndicatorCommerFlag.
     * @param value value to set the  ProcessIndicatorCommerFlag
     */
    public void setProcessIndicatorCommerFlag(String value) {
        setAttributeInternal(PROCESSINDICATORCOMMERFLAG, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CostCenterCode.
     * @return the CostCenterCode
     */
    public Number getCostCenterCode() {
        return (Number) getAttributeInternal(COSTCENTERCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CostCenterCode.
     * @param value value to set the  CostCenterCode
     */
    public void setCostCenterCode(Number value) {
        setAttributeInternal(COSTCENTERCODE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ItemCodeCombination.
     * @return the ItemCodeCombination
     */
    public String getItemCodeCombination() {
        return (String) getAttributeInternal(ITEMCODECOMBINATION);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ItemCodeCombination.
     * @param value value to set the  ItemCodeCombination
     */
    public void setItemCodeCombination(String value) {
        setAttributeInternal(ITEMCODECOMBINATION, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TotBudgetAmt.
     * @return the TotBudgetAmt
     */
    public Number getTotBudgetAmt() {
        return (Number) getAttributeInternal(TOTBUDGETAMT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TotBudgetAmt.
     * @param value value to set the  TotBudgetAmt
     */
    public void setTotBudgetAmt(Number value) {
        setAttributeInternal(TOTBUDGETAMT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Amount.
     * @return the Amount
     */
    public Number getAmount() {
        return (Number) getAttributeInternal(AMOUNT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Amount.
     * @param value value to set the  Amount
     */
    public void setAmount(Number value) {
        setAttributeInternal(AMOUNT, value);
    }

    /**
     * Gets the attribute value for STATUS1 using the alias name Status1.
     * @return the STATUS1
     */
    public String getStatus1() {
        return (String) getAttributeInternal(STATUS1);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS1 using the alias name Status1.
     * @param value value to set the STATUS1
     */
    public void setStatus1(String value) {
        setAttributeInternal(STATUS1, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> StatusLOV1.
     */
    public RowSet getStatusLOV1() {
        return (RowSet)getAttributeInternal(STATUSLOV1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
