package model.View;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 17 11:14:59 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MnjCourierInformationLineVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public MnjCourierInformationLineVOImpl() {
    }
    
}
